debug: false
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.fastcampus.projectboard: debug
    org.springframework.web.service: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: soo
    password: thisisTESTpw!@#
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    #open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  h2.console.enabled: false
  sql.init.mode: always

  # thymeleaf.cache: false

  data.rest:
      base-path: /api
      detection-strategy: annotated
  thymeleaf3:
    decoupled-logic: true

#---
#
#spring:
#  config.active.on-profile: testdb
#  datasource:
#    url: jdbc:h2:mem:board;mode=mysql
#    driver-class-name: org.h2.Driver
#  sql.init.mode: always
#  test.database.replace: none








